'use client'

import React, { createContext, useContext, useState, useEffect } from 'react'

const LanguageContext = createContext()

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState('en')

  useEffect(() => {
    const saved = localStorage.getItem('language')
    if (saved) {
      setLanguage(saved)
    }
  }, [])

  useEffect(() => {
    localStorage.setItem('language', language)
  }, [language])

  const t = (key) => {
    const translations = {
      en: {
        // Navigation
        home: 'Home',
        packages: 'Packages',
        guides: 'Guides',
        vehicles: 'Vehicles',
        contact: 'Contact',
        admin: 'Admin',
        bookNow: 'Book Now',
        login: 'Login',
        signup: 'Signup',
        logout: 'Logout',
        profile: 'Profile',
        myBookings: 'My Bookings',

        // Hero/Homepage
        welcome: 'Welcome to Tamil Nadu Tours',
        explorePackages: 'Explore our tour packages',
        discoverGuides: 'Discover experienced guides',
        rentVehicles: 'Rent vehicles for your journey',
        getInTouch: 'Get in touch with us',

        // Language & Theme
        language: 'Language',
        theme: 'Theme',
        english: 'English',
        tamil: 'Tamil',
        hindi: 'Hindi',

        // Booking Page
        completeYourBooking: 'Complete Your Booking',
        packageDetails: 'Package Details',
        guideVehicle: 'Guide & Vehicle',
        contactPayment: 'Contact & Payment',
        packageTravelDetails: 'Package & Travel Details',
        selectPackage: 'Select Package',
        choosePackage: 'Choose a package',
        selectCitiesToVisit: 'Select Cities to Visit',
        selectPlacesToVisit: 'Select Places to Visit',
        tripDuration: 'Trip Duration (days)',
        startDate: 'Start Date',
        numberOfPeople: 'Number of People',
        continueToGuideVehicle: 'Continue to Guide & Vehicle Selection',
        selectYourGuide: 'Select Your Guide',
        noGuideNeeded: 'No guide needed - I\'ll explore on my own',
        selectYourVehicle: 'Select Your Vehicle',
        noVehicleNeeded: 'No vehicle needed - I have my own transport',
        back: 'Back',
        continueToContact: 'Continue to Contact Details',
        contactInformation: 'Contact Information',
        fullName: 'Full Name',
        emailAddress: 'Email Address',
        phoneNumber: 'Phone Number',
        specialRequests: 'Special Requests (Optional)',
        enterFullName: 'Enter your full name',
        enterEmail: 'your.email@example.com',
        enterPhone: '+91 XXXXX XXXXX',
        specialRequirements: 'Any special requirements or preferences...',
        confirmBooking: 'Confirm Booking',
        bookingSummary: 'Booking Summary',
        customPackage: 'Custom Package',
        starting: 'Starting',
        travelers: 'travelers',
        guide: 'Guide',
        vehicle: 'Vehicle',
        total: 'Total',
        finalPriceNote: '* Final price may vary based on availability and seasonal rates',

        // Contact Page
        contactUs: 'Contact Us',
        planPerfectAdventure: 'Get in touch with us to plan your perfect Tamil Nadu adventure',
        travelInquiryForm: 'Travel Inquiry Form',
        firstName: 'First Name',
        lastName: 'Last Name',
        age: 'Age',
        gender: 'Gender',
        male: 'Male',
        female: 'Female',
        other: 'Other',
        preferNotToSay: 'Prefer not to say',
        numberOfPeople: 'Number of People',
        numberOfNights: 'Number of Nights',
        typeOfVehicle: 'Type of Vehicle',
        typeOfHotel: 'Type of Hotel',
        sedan: 'Sedan (4 seater)',
        suv: 'SUV (7 seater)',
        van: 'Van (12 seater)',
        bus: 'Bus (35 seater)',
        normal: 'Normal (Budget-friendly)',
        luxury: 'Luxury (Premium)',
        additionalMessage: 'Additional Message',
        tellUsPreferences: 'Tell us about your travel preferences, special requirements, or any questions...',
        submitInquiry: 'Submit Inquiry',
        businessHours: 'Business Hours',
        mondayFriday: 'Monday - Friday: 9:00 AM - 6:00 PM',
        saturday: 'Saturday: 10:00 AM - 4:00 PM',
        sunday: 'Sunday: Closed',

        // Footer
        tamilNaduTours: 'Tamil Nadu Tours',
        richHeritage: 'Discover the rich heritage and breathtaking beauty of Tamil Nadu with our expertly curated travel experiences.',
        quickLinks: 'Quick Links',
        popularDestinations: 'Popular Destinations',
        contactInfo: 'Contact Info',
        chennaiTamilNadu: 'Chennai, Tamil Nadu',
        privacyPolicy: 'Privacy Policy',
        termsOfService: 'Terms of Service',
        refundPolicy: 'Refund Policy',
        allRightsReserved: 'All rights reserved.',

        // Validation Messages
        noPackageSelected: 'No Package Selected',
        selectTravelPackage: 'Please select a travel package',
        missingInformation: 'Missing Information',
        fillContactDetails: 'Please fill in all contact details',
        missingDate: 'Missing Date',
        selectStartDate: 'Please select a start date',
        noCitiesSelected: 'No Cities Selected',
        selectAtLeastOneCity: 'Please select at least one city for your custom package',
        invalidTotal: 'Invalid Total',
        totalMustBeGreater: 'The total amount must be greater than 0',
        bookingFailed: 'Booking Failed',
        invalidAmount: 'Invalid Amount',
        totalAmountMustBeGreater: 'Total amount must be greater than 0',
        invalidBooking: 'Invalid Booking',
        bookingIdMissing: 'Booking ID is missing',
        paymentSetupFailed: 'Payment Setup Failed',
        unableToInitializePayment: 'Unable to initialize payment',
        paymentSuccessful: 'Payment Successful',
        paymentVerificationFailed: 'Payment Verification Failed',
        contactSupport: 'Please contact support',
        serverError: 'Server error',
        error: 'Error',
        fillRequiredFields: 'Please fill in all required fields',
        success: 'Success',
        inquirySubmitted: 'Your inquiry has been submitted. We\'ll contact you soon!',

        // Ready to Start
        readyToStart: 'Ready to Start Your Tamil Nadu Adventure?',
        readyToStartDesc: 'Join thousands of happy travelers who have explored Tamil Nadu with us.',

        // Homepage
        discoverBeauty: 'Discover the Beauty of Tamil Nadu',
        experienceAuthentic: 'Experience authentic Tamil culture, ancient temples, scenic hill stations and pristine beaches with our expertly curated travel experiences',
        explorePackages: 'Explore Packages',
        getInTouch: 'Get In Touch',
        whyChooseUs: 'Why Choose Us',
        expertGuides: 'Expert Guides',
        expertGuidesDesc: 'Professional multilingual guides with deep knowledge of Tamil Nadu\'s history and culture',
        comfortableTravel: 'Comfortable Travel',
        comfortableTravelDesc: 'Travel in style with experienced drivers and well-maintained modern vehicles',
        trustedService: 'Trusted Service',
        trustedServiceDesc: '10+ years of experience with thousands of satisfied travelers',
        chooseTravelStyle: 'Choose Your Travel Style',
        fixedPackages: 'Fixed Packages',
        fixedPackagesDesc: 'Pre-planned itineraries with set schedules and group tours covering popular destinations',
        viewFixedPackages: 'View Fixed Packages',
        customizedPackages: 'Customized Packages',
        customizedPackagesDesc: 'Create your own itinerary by choosing destinations, hotels and activities that suit your preferences',
        customizeYourTour: 'Customize Your Tour',
        independentVehicle: 'Independent Vehicle',
        independentVehicleDesc: 'Rent vehicles with drivers for complete flexibility in your travel schedule',
        browseVehicles: 'Browse Vehicles',
        yearsExperience: 'Years Experience',
        tourPackages: 'Tour Packages',
        happyTravelers: 'Happy Travelers',
        rating: 'Rating',
        readyToStart: 'Ready to Start Your Journey?',
        bookYourAdventure: 'Book your adventure today and create unforgettable memories in Tamil Nadu',
        bookNow: 'Book Now',
        loginToBook: 'Login to Book',
        contact: 'Contact',

        // Package Names and Descriptions
        templeTrailOfTamilNadu: 'Temple Trail of Tamil Nadu',
        templeTrailDescription: "Explore the magnificent temples of Tamil Nadu including Meenakshi Temple, Brihadeeswarar Temple, and more. A spiritual journey through ancient architecture.",
        hillStationRetreat: 'Hill Station Retreat',
        hillStationRetreatDescription: "Escape to the cool climate of Tamil Nadu's hill stations. Visit Ooty, Kodaikanal, and Yercaud.",
        coastalParadiseTour: 'Coastal Paradise Tour',
        coastalParadiseTourDescription: 'Discover the beautiful beaches and coastal towns of Tamil Nadu.',
        buildYourOwnAdventure: 'Build Your Own Adventure',
        buildYourOwnAdventureDescription: 'Create your perfect Tamil Nadu itinerary by selecting cities and attractions.',
        ashokLeylandFactoryVisit: 'Ashok Leyland Factory Visit',
        ashokLeylandFactoryVisitDescription: 'Explore one of India\'s leading automobile manufacturers.',
        automotivePlantVisit: 'Automotive Plant Visit',
        automotivePlantVisitDescription: 'An industrial visit to a local manufacturing facility.',

        // Additional translations
        days: 'days',
        places: 'places',
        reviews: 'reviews',
        person: 'person',
        edit: 'Edit',
        delete: 'Delete',
        viewDetails: 'View Details',
        customizePackage: 'Customize Package',
        creating: 'Creating...',
        createPackage: 'Create Package',
        cancel: 'Cancel',
        images: 'Images',
        addImageURL: 'Add image URL',
        addAPlace: 'Add a place',
        numberOfReviews: 'Number of Reviews',
        durationDays: 'Duration (days)',
        price: 'Price (₹)',
        rating: 'Rating',
        enterPackageDescription: 'Enter package description',
        description: 'Description',
        enterPackageName: 'Enter package name',
        packageName: 'Package Name',
        packageType: 'Package Type',
        selectType: 'Select type',
        fixedPackage: 'Fixed Package',
        customizedPackage: 'Customized Package',
        industrialVisit: 'Industrial Visit',
        accessDenied: 'Access Denied',
        adminPrivilegesRequired: 'Admin privileges required',
        backToPackages: 'Back to Packages',
        createNewPackage: 'Create New Package',
        addNewTravelPackage: 'Add a new travel package',
        packageDetails: 'Package Details',
      },
      ta: {
        // Navigation
        home: 'முகப்பு',
        packages: 'தொகுப்புகள்',
        guides: 'வழிகாட்டிகள்',
        vehicles: 'வாகனங்கள்',
        contact: 'தொடர்பு',
        admin: 'நிர்வாகம்',
        bookNow: 'இப்போது முன்பதிவு செய்ய',
        login: 'உள்நுழை',
        signup: 'பதிவு செய்',
        logout: 'வெளியேறு',
        profile: 'சுயவிவரம்',
        myBookings: 'எனது முன்பதிவுகள்',

        // Hero/Homepage
        welcome: 'தமிழ்நாடு சுற்றுலாவுக்கு வரவேற்கிறோம்',
        explorePackages: 'எங்கள் சுற்றுலா தொகுப்புகளை ஆராயுங்கள்',
        discoverGuides: 'அனுபவமிக்க வழிகாட்டிகளை கண்டறியுங்கள்',
        rentVehicles: 'உங்கள் பயணத்திற்கு வாகனங்களை வாடகைக்கு எடுங்கள்',
        getInTouch: 'எங்களுடன் தொடர்பு கொள்ளுங்கள்',

        // Language & Theme
        language: 'மொழி',
        theme: 'தீம்',
        english: 'ஆங்கிலம்',
        tamil: 'தமிழ்',
        hindi: 'இந்தி',

        // Booking Page
        completeYourBooking: 'உங்கள் முன்பதிவை முடிக்கவும்',
        packageDetails: 'தொகுப்பு விவரங்கள்',
        guideVehicle: 'வழிகாட்டி & வாகனம்',
        contactPayment: 'தொடர்பு & கட்டணம்',
        packageTravelDetails: 'தொகுப்பு & பயண விவரங்கள்',
        selectPackage: 'தொகுப்பைத் தேர்ந்தெடுக்கவும்',
        choosePackage: 'ஒரு தொகுப்பைத் தேர்ந்தெடுக்கவும்',
        selectCitiesToVisit: 'பார்க்க வேண்டிய நகரங்களைத் தேர்ந்தெடுக்கவும்',
        selectPlacesToVisit: 'பார்க்க வேண்டிய இடங்களைத் தேர்ந்தெடுக்கவும்',
        tripDuration: 'பயண காலம் (நாட்கள்)',
        startDate: 'தொடக்க தேதி',
        numberOfPeople: 'மக்கள் எண்ணிக்கை',
        continueToGuideVehicle: 'வழிகாட்டி & வாகன தேர்வுக்கு தொடரவும்',
        selectYourGuide: 'உங்கள் வழிகாட்டியைத் தேர்ந்தெடுக்கவும்',
        noGuideNeeded: 'வழிகாட்டி தேவையில்லை - நான் தானே ஆராய்வேன்',
        selectYourVehicle: 'உங்கள் வாகனத்தைத் தேர்ந்தெடுக்கவும்',
        noVehicleNeeded: 'வாகனம் தேவையில்லை - எனக்கு எனது சொந்த போக்குவரத்து உள்ளது',
        back: 'பின்னால்',
        continueToContact: 'தொடர்பு விவரங்களுக்கு தொடரவும்',
        contactInformation: 'தொடர்பு தகவல்',
        fullName: 'முழு பெயர்',
        emailAddress: 'மின்னஞ்சல் முகவரி',
        phoneNumber: 'தொலைபேசி எண்',
        specialRequests: 'சிறப்பு கோரிக்கைகள் (விருப்பமானது)',
        enterFullName: 'உங்கள் முழு பெயரை உள்ளீடு செய்யவும்',
        enterEmail: 'your.email@example.com',
        enterPhone: '+91 XXXXX XXXXX',
        specialRequirements: 'எந்த சிறப்பு தேவைகள் அல்லது விருப்பங்களும்...',
        confirmBooking: 'முன்பதிவை உறுதிப்படுத்து',
        bookingSummary: 'முன்பதிவு சுருக்கம்',
        customPackage: 'தனிப்பயன் தொகுப்பு',
        starting: 'தொடங்குதல்',
        travelers: 'பயணிகள்',
        guide: 'வழிகாட்டி',
        vehicle: 'வாகனம்',
        total: 'மொத்தம்',
        finalPriceNote: '* இறுதி விலை கிடைப்பு மற்றும் பருவ கட்டணங்களின் அடிப்படையில் மாறலாம்',

        // Contact Page
        contactUs: 'எங்களை தொடர்பு கொள்ளவும்',
        planPerfectAdventure: 'உங்கள் சரியான தமிழ்நாடு சாகசத்தை திட்டமிட எங்களை தொடர்பு கொள்ளவும்',
        travelInquiryForm: 'பயண விசாரணை படிவம்',
        firstName: 'முதல் பெயர்',
        lastName: 'கடைசி பெயர்',
        age: 'வயது',
        gender: 'பாலினம்',
        male: 'ஆண்',
        female: 'பெண்',
        other: 'மற்றவை',
        preferNotToSay: 'சொல்ல விரும்பவில்லை',
        numberOfPeople: 'மக்கள் எண்ணிக்கை',
        numberOfNights: 'இரவுகளின் எண்ணிக்கை',
        typeOfVehicle: 'வாகன வகை',
        typeOfHotel: 'ஹோட்டல் வகை',
        sedan: 'செடான் (4 இருக்கை)',
        suv: 'SUV (7 இருக்கை)',
        van: 'வேன் (12 இருக்கை)',
        bus: 'பஸ் (35 இருக்கை)',
        normal: 'சாதாரண (பட்ஜெட் நட்பு)',
        luxury: 'சொகுசு (பிரீமியம்)',
        additionalMessage: 'கூடுதல் செய்தி',
        tellUsPreferences: 'உங்கள் பயண விருப்பங்கள், சிறப்பு தேவைகள் அல்லது எந்த கேள்விகளையும் எங்களிடம் சொல்லுங்கள்...',
        submitInquiry: 'விசாரணையை சமர்ப்பிக்கவும்',
        businessHours: 'வணிக நேரம்',
        mondayFriday: 'திங்கள் - வெள்ளி: காலை 9:00 - மாலை 6:00',
        saturday: 'சனிக்கிழமை: காலை 10:00 - மாலை 4:00',
        sunday: 'ஞாயிறு: மூடப்பட்டது',

        // Footer
        tamilNaduTours: 'தமிழ்நாடு சுற்றுலா',
        richHeritage: 'எங்கள் நிபுணத்துவமான பயண அனுபவங்களுடன் தமிழ்நாட்டின் செழிப்பான மரபு மற்றும் மூச்சடைக்கும் அழகை கண்டறியுங்கள்.',
        quickLinks: 'விரைவு இணைப்புகள்',
        popularDestinations: 'பிரபலமான இலக்குகள்',
        contactInfo: 'தொடர்பு தகவல்',
        chennaiTamilNadu: 'சென்னை, தமிழ்நாடு',
        privacyPolicy: 'தனியுரிமைக் கொள்கை',
        termsOfService: 'சேவை விதிமுறைகள்',
        refundPolicy: 'திரும்பப் பெறும் கொள்கை',
        allRightsReserved: 'அனைத்து உரிமைகளும் பாதுகாக்கப்பட்டவை.',

        // Validation Messages
        noPackageSelected: 'தொகுப்பு தேர்ந்தெடுக்கப்படவில்லை',
        selectTravelPackage: 'தயவுசெய்து ஒரு பயண தொகுப்பைத் தேர்ந்தெடுக்கவும்',
        missingInformation: 'தகவல் இல்லை',
        fillContactDetails: 'அனைத்து தொடர்பு விவரங்களையும் நிரப்பவும்',
        missingDate: 'தேதி இல்லை',
        selectStartDate: 'தயவுசெய்து தொடக்க தேதியைத் தேர்ந்தெடுக்கவும்',
        noCitiesSelected: 'நகரங்கள் தேர்ந்தெடுக்கப்படவில்லை',
        selectAtLeastOneCity: 'உங்கள் தனிப்பயன் தொகுப்புக்கு குறைந்தது ஒரு நகரத்தையாவது தேர்ந்தெடுக்கவும்',
        invalidTotal: 'தவறான மொத்தம்',
        totalMustBeGreater: 'மொத்த தொகை 0-க்கு மேல் இருக்க வேண்டும்',
        bookingFailed: 'முன்பதிவு தோல்வியடைந்தது',
        invalidAmount: 'தவறான தொகை',
        totalAmountMustBeGreater: 'மொத்த தொகை 0-க்கு மேல் இருக்க வேண்டும்',
        invalidBooking: 'தவறான முன்பதிவு',
        bookingIdMissing: 'முன்பதிவு ஐடி இல்லை',
        paymentSetupFailed: 'கட்டண அமைப்பு தோல்வியடைந்தது',
        unableToInitializePayment: 'கட்டணத்தை துவக்க இயலவில்லை',
        paymentSuccessful: 'கட்டணம் வெற்றிகரமாக',
        paymentVerificationFailed: 'கட்டண சரிபார்ப்பு தோல்வியடைந்தது',
        contactSupport: 'தயவுசெய்து ஆதரவை தொடர்பு கொள்ளவும்',
        serverError: 'சர்வர் பிழை',
        error: 'பிழை',
        fillRequiredFields: 'அனைத்து தேவையான புலங்களையும் நிரப்பவும்',
        success: 'வெற்றி',
        inquirySubmitted: 'உங்கள் விசாரணை சமர்ப்பிக்கப்பட்டது. விரைவில் உங்களை தொடர்பு கொள்வோம்!',

        // Ready to Start
        readyToStart: 'உங்கள் தமிழ்நாடு சாகசத்தை தொடங்க தயாரா?',
        readyToStartDesc: 'எங்களுடன் தமிழ்நாட்டை ஆராய்ந்த மகிழ்ச்சியான பயணிகளின் ஆயிரக்கணக்கானவர்களுடன் இணையுங்கள்.',

        // Package Names and Descriptions
        templeTrailOfTamilNadu: 'தமிழ்நாட்டின் கோவில் பாதை',
        templeTrailDescription: "மீனாட்சி அம்மன் கோவில், பிரிஹதீஸ்வரர் கோவில் போன்ற தமிழ்நாட்டின் பிரமாண்டமான கோவில்களை ஆராயுங்கள். பழமையான கட்டிடக்கலையின் ஆன்மீக பயணம்.",
        hillStationRetreat: 'மலை நிலையம் ஓய்வு',
        hillStationRetreatDescription: "தமிழ்நாட்டின் குளிர்ந்த மலை நிலையங்களுக்கு தப்பி செல்லுங்கள். ஊட்டி, கொடைக்கானல், ஏர்காட்டை பார்வையிடுங்கள்.",
        coastalParadiseTour: 'கடற்கரை சொர்க்க சுற்றுலா',
        coastalParadiseTourDescription: 'தமிழ்நாட்டின் அழகான கடற்கரைகள் மற்றும் கடற்கரை நகரங்களை கண்டறியுங்கள்.',
        buildYourOwnAdventure: 'உங்கள் சொந்த சாகசத்தை உருவாக்குங்கள்',
        buildYourOwnAdventureDescription: 'நகரங்கள் மற்றும் கவர்ச்சிகளைத் தேர்ந்தெடுப்பதன் மூலம் உங்கள் சரியான தமிழ்நாடு பயணத்திட்டத்தை உருவாக்குங்கள்.',
        ashokLeylandFactoryVisit: 'அசோக் லேலாந்த் தொழிற்சாலை பார்வை',
        ashokLeylandFactoryVisitDescription: 'இந்தியாவின் முன்னணி ஆட்டோமோட்டிவ் உற்பத்தியாளர்களில் ஒருவரை ஆராயுங்கள்.',
        automotivePlantVisit: 'ஆட்டோமோட்டிவ் தொழிற்சாலை பார்வை',
        automotivePlantVisitDescription: 'ஒரு உள்ளூரி உற்பத்தி நிறுவனத்திற்கு ஒரு தொழில்துறை பார்வை.',

        // Additional translations
        days: 'நாட்கள்',
        places: 'இடங்கள்',
        reviews: 'மதிப்பீடுகள்',
        person: 'நபர்',
        edit: 'திருத்து',
        delete: 'நீக்கு',
        viewDetails: 'விவரங்களைப் பார்க்க',
        customizePackage: 'தொகுப்பை தனிப்பயனாக்கு',
        creating: 'உருவாக்குகிறது...',
        createPackage: 'தொகுப்பை உருவாக்கு',
        cancel: 'ரத்து செய்',
        images: 'படங்கள்',
        addImageURL: 'பட URL சேர்க்க',
        addAPlace: 'ஒரு இடத்தை சேர்க்க',
        numberOfReviews: 'மதிப்பீடுகளின் எண்ணிக்கை',
        durationDays: 'காலம் (நாட்கள்)',
        price: 'விலை (₹)',
        rating: 'மதிப்பீடு',
        enterPackageDescription: 'தொகுப்பு விளக்கத்தை உள்ளீடு செய்யவும்',
        description: 'விளக்கம்',
        enterPackageName: 'தொகுப்பு பெயரை உள்ளீடு செய்யவும்',
        packageName: 'தொகுப்பு பெயர்',
        packageType: 'தொகுப்பு வகை',
        selectType: 'வகையைத் தேர்ந்தெடுக்கவும்',
        fixedPackage: 'நிலையான தொகுப்பு',
        customizedPackage: 'தனிப்பயன் தொகுப்பு',
        industrialVisit: 'தொழில்துறை பார்வை',
        accessDenied: 'அணுகல் மறுக்கப்பட்டது',
        adminPrivilegesRequired: 'நிர்வாக சலுகைகள் தேவை',
        backToPackages: 'தொகுப்புகளுக்கு திரும்பு',
        createNewPackage: 'புதிய தொகுப்பை உருவாக்கு',
        addNewTravelPackage: 'புதிய பயண தொகுப்பை சேர்க்க',
        packageDetails: 'தொகுப்பு விவரங்கள்',
      },
      hi: {
        // Navigation
        home: 'होम',
        packages: 'पैकेज',
        guides: 'गाइड',
        vehicles: 'वाहन',
        contact: 'संपर्क',
        admin: 'एडमिन',
        bookNow: 'अभी बुक करें',
        login: 'लॉग इन',
        signup: 'साइन अप',
        logout: 'लॉग आउट',
        profile: 'प्रोफ़ाइल',
        myBookings: 'मेरी बुकिंग',

        // Hero/Homepage
        welcome: 'तमिलनाडु टूर्स में आपका स्वागत है',
        explorePackages: 'हमारे टूर पैकेज एक्सप्लोर करें',
        discoverGuides: 'अनुभवी गाइड खोजें',
        rentVehicles: 'अपनी यात्रा के लिए वाहन किराए पर लें',
        getInTouch: 'हमसे संपर्क करें',

        // Language & Theme
        language: 'भाषा',
        theme: 'थीम',
        english: 'अंग्रेजी',
        tamil: 'तमिल',
        hindi: 'हिंदी',

        // Booking Page
        completeYourBooking: 'अपनी बुकिंग पूरी करें',
        packageDetails: 'पैकेज विवरण',
        guideVehicle: 'गाइड और वाहन',
        contactPayment: 'संपर्क और भुगतान',
        packageTravelDetails: 'पैकेज और यात्रा विवरण',
        selectPackage: 'पैकेज चुनें',
        choosePackage: 'एक पैकेज चुनें',
        selectCitiesToVisit: 'देखने के लिए शहर चुनें',
        selectPlacesToVisit: 'देखने के लिए स्थान चुनें',
        tripDuration: 'यात्रा अवधि (दिन)',
        startDate: 'प्रारंभ तिथि',
        numberOfPeople: 'लोगों की संख्या',
        continueToGuideVehicle: 'गाइड और वाहन चयन पर जारी रखें',
        selectYourGuide: 'अपना गाइड चुनें',
        noGuideNeeded: 'गाइड की आवश्यकता नहीं - मैं स्वयं एक्सप्लोर करूंगा',
        selectYourVehicle: 'अपना वाहन चुनें',
        noVehicleNeeded: 'वाहन की आवश्यकता नहीं - मेरे पास अपना परिवहन है',
        back: 'वापस',
        continueToContact: 'संपर्क विवरण पर जारी रखें',
        contactInformation: 'संपर्क जानकारी',
        fullName: 'पूरा नाम',
        emailAddress: 'ईमेल पता',
        phoneNumber: 'फोन नंबर',
        specialRequests: 'विशेष अनुरोध (वैकल्पिक)',
        enterFullName: 'अपना पूरा नाम दर्ज करें',
        enterEmail: 'your.email@example.com',
        enterPhone: '+91 XXXXX XXXXX',
        specialRequirements: 'कोई विशेष आवश्यकताएं या प्राथमिकताएं...',
        confirmBooking: 'बुकिंग की पुष्टि करें',
        bookingSummary: 'बुकिंग सारांश',
        customPackage: 'कस्टम पैकेज',
        starting: 'शुरू',
        travelers: 'यात्री',
        guide: 'गाइड',
        vehicle: 'वाहन',
        total: 'कुल',
        finalPriceNote: '* अंतिम मूल्य उपलब्धता और मौसमी दरों के आधार पर भिन्न हो सकता है',

        // Contact Page
        contactUs: 'हमसे संपर्क करें',
        planPerfectAdventure: 'अपनी परफेक्ट तमिलनाडु एडवेंचर प्लान करने के लिए हमसे संपर्क करें',
        travelInquiryForm: 'यात्रा पूछताछ फॉर्म',
        firstName: 'पहला नाम',
        lastName: 'अंतिम नाम',
        age: 'आयु',
        gender: 'लिंग',
        male: 'पुरुष',
        female: 'महिला',
        other: 'अन्य',
        preferNotToSay: 'बताना नहीं चाहते',
        numberOfPeople: 'लोगों की संख्या',
        numberOfNights: 'रातों की संख्या',
        typeOfVehicle: 'वाहन का प्रकार',
        typeOfHotel: 'होटल का प्रकार',
        sedan: 'सेडान (4 सीटर)',
        suv: 'SUV (7 सीटर)',
        van: 'वैन (12 सीटर)',
        bus: 'बस (35 सीटर)',
        normal: 'सामान्य (बजट फ्रेंडली)',
        luxury: 'लक्जरी (प्रीमियम)',
        additionalMessage: 'अतिरिक्त संदेश',
        tellUsPreferences: 'हमें अपनी यात्रा प्राथमिकताओं, विशेष आवश्यकताओं या किसी भी प्रश्न के बारे में बताएं...',
        submitInquiry: 'पूछताछ सबमिट करें',
        businessHours: 'व्यापारिक घंटे',
        mondayFriday: 'सोमवार - शुक्रवार: सुबह 9:00 - शाम 6:00',
        saturday: 'शनिवार: सुबह 10:00 - शाम 4:00',
        sunday: 'रविवार: बंद',

        // Footer
        tamilNaduTours: 'तमिलनाडु टूर्स',
        richHeritage: 'हमारे विशेषज्ञ रूप से तैयार किए गए यात्रा अनुभवों के साथ तमिलनाडु की समृद्ध विरासत और मनमोहक सुंदरता की खोज करें।',
        quickLinks: 'त्वरित लिंक',
        popularDestinations: 'लोकप्रिय गंतव्य',
        contactInfo: 'संपर्क जानकारी',
        chennaiTamilNadu: 'चेन्नई, तमिलनाडु',
        privacyPolicy: 'गोपनीयता नीति',
        termsOfService: 'सेवा की शर्तें',
        refundPolicy: 'रिफंड नीति',
        allRightsReserved: 'सभी अधिकार सुरक्षित।',

        // Validation Messages
        noPackageSelected: 'कोई पैकेज नहीं चुना गया',
        selectTravelPackage: 'कृपया एक यात्रा पैकेज चुनें',
        missingInformation: 'जानकारी गुम',
        fillContactDetails: 'कृपया सभी संपर्क विवरण भरें',
        missingDate: 'तिथि गुम',
        selectStartDate: 'कृपया प्रारंभ तिथि चुनें',
        noCitiesSelected: 'कोई शहर नहीं चुना गया',
        selectAtLeastOneCity: 'कृपया अपने कस्टम पैकेज के लिए कम से कम एक शहर चुनें',
        invalidTotal: 'अमान्य कुल',
        totalMustBeGreater: 'कुल राशि 0 से अधिक होनी चाहिए',
        bookingFailed: 'बुकिंग विफल',
        invalidAmount: 'अमान्य राशि',
        totalAmountMustBeGreater: 'कुल राशि 0 से अधिक होनी चाहिए',
        invalidBooking: 'अमान्य बुकिंग',
        bookingIdMissing: 'बुकिंग आईडी गुम',
        paymentSetupFailed: 'भुगतान सेटअप विफल',
        unableToInitializePayment: 'भुगतान शुरू करने में असमर्थ',
        paymentSuccessful: 'भुगतान सफल',
        paymentVerificationFailed: 'भुगतान सत्यापन विफल',
        contactSupport: 'कृपया सहायता से संपर्क करें',
        serverError: 'सर्वर त्रुटि',
        error: 'त्रुटि',
        fillRequiredFields: 'कृपया सभी आवश्यक फ़ील्ड भरें',
        success: 'सफलता',
        inquirySubmitted: 'आपकी पूछताछ सबमिट कर दी गई है। हम जल्द ही आपसे संपर्क करेंगे!',

        // Ready to Start
        readyToStart: 'अपनी तमिलनाडु एडवेंचर शुरू करने के लिए तैयार हैं?',
        readyToStartDesc: 'हमारे साथ तमिलनाडु की खोज करने वाले हजारों खुश यात्रियों में शामिल हों।',

        // Package Names and Descriptions
        templeTrailOfTamilNadu: 'तमिलनाडु का मंदिर मार्ग',
        templeTrailDescription: "मीनाक्षी मंदिर, बृहदीश्वर मंदिर सहित तमिलनाडु के भव्य मंदिरों की खोज करें। प्राचीन वास्तुकला के माध्यम से एक आध्यात्मिक यात्रा।",
        hillStationRetreat: 'हिल स्टेशन रिट्रीट',
        hillStationRetreatDescription: "तमिलनाडु के हिल स्टेशनों की ठंडी जलवायु में भागें। ऊटी, कोडाईकनाल, और येरकाड का दौरा करें।",
        coastalParadiseTour: 'तटीय स्वर्ग दौरा',
        coastalParadiseTourDescription: 'तमिलनाडु के सुंदर समुद्र तटों और तटीय शहरों की खोज करें।',
        buildYourOwnAdventure: 'अपना अपना साहसिक कार्य बनाएं',
        buildYourOwnAdventureDescription: 'शहरों और आकर्षणों का चयन करके अपना आदर्श तमिलनाडु यात्रा कार्यक्रम बनाएं।',
        ashokLeylandFactoryVisit: 'अशोक लेलैंड फैक्टरी विजिट',
        ashokLeylandFactoryVisitDescription: 'भारत के प्रमुख ऑटोमोटिव निर्माताओं में से एक की खोज करें।',
        automotivePlantVisit: 'ऑटोमोटिव प्लांट विजिट',
        automotivePlantVisitDescription: 'एक स्थानीय विनिर्माण सुविधा का एक औद्योगिक दौरा।',

        // Additional translations
        days: 'दिन',
        places: 'स्थान',
        reviews: 'समीक्षाएं',
        person: 'व्यक्ति',
        edit: 'संपादित करें',
        delete: 'हटाएं',
        viewDetails: 'विवरण देखें',
        customizePackage: 'पैकेज अनुकूलित करें',
        creating: 'बनाया जा रहा है...',
        createPackage: 'पैकेज बनाएं',
        cancel: 'रद्द करें',
        images: 'छवियां',
        addImageURL: 'छवि URL जोड़ें',
        addAPlace: 'एक स्थान जोड़ें',
        numberOfReviews: 'समीक्षाओं की संख्या',
        durationDays: 'अवधि (दिन)',
        price: 'मूल्य (₹)',
        rating: 'रेटिंग',
        enterPackageDescription: 'पैकेज विवरण दर्ज करें',
        description: 'विवरण',
        enterPackageName: 'पैकेज नाम दर्ज करें',
        packageName: 'पैकेज नाम',
        packageType: 'पैकेज प्रकार',
        selectType: 'प्रकार चुनें',
        fixedPackage: 'निश्चित पैकेज',
        customizedPackage: 'अनुकूलित पैकेज',
        industrialVisit: 'औद्योगिक दौरा',
        accessDenied: 'पहुंच अस्वीकृत',
        adminPrivilegesRequired: 'व्यवस्थापक विशेषाधिकार आवश्यक',
        backToPackages: 'पैकेजों पर वापस जाएं',
        createNewPackage: 'नया पैकेज बनाएं',
        addNewTravelPackage: 'नया यात्रा पैकेज जोड़ें',
        packageDetails: 'पैकेज विवरण',

        // Homepage
        discoverBeauty: 'तमिलनाडु की सुंदरता की खोज करें',
        experienceAuthentic: 'हमारे विशेषज्ञ रूप से तैयार किए गए यात्रा अनुभवों के साथ प्रामाणिक तमिल संस्कृति, प्राचीन मंदिर, मनमोहक पहाड़ी स्टेशन और निर्मल समुद्र तट का अनुभव करें',
        explorePackages: 'पैकेज एक्सप्लोर करें',
        getInTouch: 'संपर्क करें',
        whyChooseUs: 'हमें क्यों चुनें',
        expertGuides: 'विशेषज्ञ गाइड',
        expertGuidesDesc: 'तमिलनाडु के इतिहास और संस्कृति के गहरे ज्ञान के साथ पेशेवर बहुभाषी गाइड',
        comfortableTravel: 'आरामदायक यात्रा',
        comfortableTravelDesc: 'सुरक्षित यात्रा के लिए अनुभवी ड्राइवरों के साथ आधुनिक, अच्छी तरह से रखरखाव किए गए वाहन',
        trustedService: 'विश्वसनीय सेवा',
        trustedServiceDesc: 'हजारों संतुष्ट यात्रियों के साथ 10+ साल का अनुभव',
        chooseTravelStyle: 'अपनी यात्रा शैली चुनें',
        fixedPackages: 'निश्चित पैकेज',
        fixedPackagesDesc: 'सेट शेड्यूल और ग्रुप टूर के साथ लोकप्रिय गंतव्यों को कवर करने वाले पूर्व नियोजित यात्रा कार्यक्रम',
        viewFixedPackages: 'निश्चित पैकेज देखें',
        customizedPackages: 'अनुकूलित पैकेज',
        customizedPackagesDesc: 'गंतव्य, होटल और गतिविधियाँ चुनकर अपना खुद का यात्रा कार्यक्रम बनाएँ जो आपकी पसंद के अनुरूप हों',
        customizeYourTour: 'अपनी यात्रा अनुकूलित करें',
        independentVehicle: 'स्वतंत्र वाहन',
        independentVehicleDesc: 'अपनी यात्रा शेड्यूल में पूर्ण लचीलापन के लिए ड्राइवर के साथ वाहन किराए पर लें',
        browseVehicles: 'वाहन ब्राउज़ करें',
        yearsExperience: 'साल का अनुभव',
        tourPackages: 'यात्रा पैकेज',
        happyTravelers: 'खुश यात्री',
        rating: 'रेटिंग',
        readyToStart: 'अपनी यात्रा शुरू करने के लिए तैयार हैं?',
        bookYourAdventure: 'आज अपनी तमिलनाडु एडवेंचर बुक करें और आजीवन यादें बनाएँ',
        bookNow: 'अभी बुक करें',
        loginToBook: 'बुक करने के लिए लॉगिन करें',
        contact: 'संपर्क',
      },
    }
    return translations[language]?.[key] || key
  }

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider')
  }
  return context
}
